### PR TITLE
Support proxy, use `request` instead of `download`

### LINKED ISSUE #12: Installation script fails behind proxy
The script `install.js` which runs on installation fails downloading from `http://dl.nwjs.io/v*` behind proxy.

both `$http_proxy` shell variable and `npm config proxy` are set properly.

Probably problem with the `download` package that is being used, which uses a package called `got` which apparently does not support proxy like this.

It would be great if we can fix this. I am ready to assist if I can be useful.

Thanks.

### PR DESCRIPTION
**Pull request by nisargjhaveri**
fixes #12.

Please review and check the script and ensure it works perfectly without proxy, too as I can't check without proxy. It works with proxy in my case.

Also, I'm not sure of the implementation. Please have a second eye. :)

### CODE REVIEW

**Comment by shama** [comment]
Thanks! I kinda like `download` though. What if we tried `tunnel` instead?

Try `npm i tunnel` and adding this option to `Download`:

```
agent: require('tunnel').httpsOverHttp({
  proxy: { host: process.env.http_proxy }
})
```

**Comment by nisargjhaveri** [comment]
I tried many solution. One of them was with `tunnel` also. But they were quick experiments.

I'll try once more with the solution you gave and let you know.

**Comment by nisargjhaveri** [comment]
I added the `agent` field with `extract` and other options in `Download`, it gives "tunneling socket could not be established, cause=getaddrinfo ENOTFOUND"

**Comment by nisargjhaveri** [comment]
And I don't see any problems with `request`.

The main problem with `download` is the underlying module `got` which does not handle proxy very well by itself.

**Comment by shama** [comment]
Hmm dang, thanks for trying @nisargjhaveri! Let me play around a bit and if I can't get something working I'll merge this.

@sindresorhus or @kevva any tips on how to get proxies working again for `download`?

**Comment by kevva** [comment]
@shama, use `download@3` for now. It uses the same API but with `request` instead of `got`.

**Comment by shama** [comment]
Fixed by #16

**Pull request closed without merging**
