### PR TITLE
install NW.js v0.13.0 alpha 7 SDK build

### PR DESCRIPTION
**Pull request by Mithgol**
NW.js v0.13.0 alpha 7 [is released](https://groups.google.com/d/msg/nwjs-general/HF7InrhFxqw/4v7SdZWOBwAJ), and thus I am upgrading the effect of #32.

### CODE REVIEW

**Comment by shama** [comment]
:+1: Feel free to push and publish directly too. Let me know if you run into trouble accessing things. Thanks!

**Comment by Mithgol** [comment]
Okay, I've just run `npm publish --tag alpha7sdk`, I hope the tag was correct.

**Comment by shama** [comment]
:metal:

**Comment by Mithgol** [comment]
Starting from NW.js v0.13.0 beta 3 SDK build, the tag will be simply `sdk` so that the tag is more reusable.

**Pull request merged**
